import { day1 } from "./challenges/day1";
import { day10 } from "./challenges/day10";
import { day11 } from "./challenges/day11";
import { day2 } from "./challenges/day2";
import { day3 } from "./challenges/day3";
import { day4 } from "./challenges/day4";
import { day5 } from "./challenges/day5";
import { day6 } from "./challenges/day6";
import { day7 } from "./challenges/day7";
import { day8 } from "./challenges/day8";
import { day9 } from "./challenges/day9";

// day1();
// day2();
// day3();
// day4();
// day5();
// day6();
// day7();
// day8();
// day9();
// day10();
day11();
